version: "3.9"
services:
  commands:
    build: ./apis
    ports:
      - "8000:4000"
    depends_on:
      - mqtt
    volumes:
      - "./apis/app.py:/app/app.py"
    networks:
      - cv_searching

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    ports:
        - "1883:1883"
        - "9001:9001"
    networks:
        - cv_searching
  broker:
    build: ./broker
    volumes:
      - "./broker/example_susc.py:/app/example_susc.py"
    networks:
      - cv_searching
    profiles:
      - donotstart
networks:
  cv_searching:
    name: cv_searching
    driver: bridge
